# Generated by Django 4.2.1 on 2023-06-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('strip1', models.CharField(max_length=100)),
                ('strip2', models.CharField(max_length=100)),
                ('strip3', models.CharField(max_length=100)),
                ('strip4', models.CharField(max_length=100)),
                ('strip5', models.CharField(max_length=100)),
                ('strip6', models.CharField(max_length=100)),
                ('win', models.IntegerField()),
            ],
        ),
    ]
